### ISSUE TITLE
automations à une source

### ISSUE THREAD

**Issue by vberthiaume** [GRIS-UdeM/ZirkOSC#14]
Au début, je me suis dit, au lieu d'avoir 16 paramètres pour les xy des 8 sources, on pourrait garder seulement 2 paramètres pour le xy de la source 1, et quand on coche link movement (checkbox présent dans l'octogris, à ajouter dans zirkosc), toutes les sources présentes dans le plugin se déplacent suivant les mouvements de la source 1, que ce soit à l'écriture ou à la lecture d'automations.

Par contre, cela voudrait dire qu'on ne pourrait avoir de mouvements indépendants des sources 2-8. Genre, il serait impossible d'enregistrer une automation pour déplacer uniquement la source 3. Donc cela me dit qu'il faudrait garder les 16 paramètres de position, et quand on coche link movement, les sources 2-8 ignorent leurs automations (si des automations on été écrites en mode indépendant) et suivent celle de la source 1 (ou en fait, les sources non-sélectionnées ignorent leur automations respectives et suivent celle de la source sélectionnée).

**Comment by vberthiaume** [comment]
voir #12 pour des tests

**Comment by Normandeau** [comment]
Oui je pense que c'est la bonne stratégie à adopter. Comme cela on a la possibilité de faire des mouvements de groupe sans que cela monopolise toutes les ressources du DAW, et si certains utilisateurs le désirent, ils peuvent écrire des trajectoires séparées à l'intérieur d'un fichier multiphonique (quoique je suggérerais alors dans la manuel de travailler sur des pistes différentes tout simplement).

**Comment by Normandeau** [comment]
J'ai changé deux préférences importantes dans Logic et dans DP avec lesquelles j'ai obtenu un certain succès avec les GRMTools.
Dans DP9, il s'agit de l'option Pre-gen qui réglé un problème de surcharge de CPU:
![dp9 pre-gen](https://cloud.githubusercontent.com/assets/8959779/8547739/0a422530-24c1-11e5-8aae-52cf13536dd9.jpg)

Dans LogicX, il s'agit de la fonction Sample Acurate Automation:
![logicx sample acurate](https://cloud.githubusercontent.com/assets/8959779/8547800/820ef91c-24c1-11e5-9c91-ad442d84f206.jpg)

Cela devrait normalement nous donner une plus grande précision dans l'écriture de l'automation. Dans les faits cela surcharge complètement le CPU avec les GRMTools du moins. En l'enlevant, cela règle le problème pour ces derniers.

Pour nous cependant aucun changement:
DP9:
![dp9 zirkosc222 pre-gen](https://cloud.githubusercontent.com/assets/8959779/8548247/fbce5106-24c3-11e5-8b95-03511d4ae487.jpg)

LogicX. Que ce soit avec un fichier stéréo ou octophonique, ça dérape:
![logic zirkosc222 samaccoff](https://cloud.githubusercontent.com/assets/8959779/8548263/19aaacf6-24c4-11e5-85a3-b38c32064b9a.jpg)
