### ISSUE TITLE
Initialisation du port OSC

### ISSUE THREAD

**Issue by DominicThibault** [GRIS-UdeM/ZirkOSC#18]
Sous Reaper64.
Au chargement, la boîte à chiffre du port OSC doit être réinitialisée (focus puis enter) afin que la transmission des messages OSC commence. Et ce même si le # de port est le bon.

À tester dans d'autres séquenceurs.

**Comment by vberthiaume** [comment]
je n'ai pas ce problème?

**Comment by DominicThibault** [comment]
Ce problème n'est que sous Reaper. VST autant que AU. Dans DP, il n'y a pas ce problème.

Voici comment je reproduis le problème:
1) Ouvrir et démarrer Jack
2) Ouvrir Zirkonium Server
3) Ouvrir une nouvelle session Reaper.
4) Créer une piste
5) Charger ZirkOSC3 sur la piste.
6) Changer les valeurs "Nbr sources" à 2 et "1st source ID" à 1. 
7) Bouger les sources avec l'interface graphique, les valeurs ne sont pas transmises au Zirkonium Server
8) Cliquer dans la boîte "ZKM OSC port" et appuyer "enter"
9) Les valeurs sont envoyées au ZIrkonium Server

**Comment by vberthiaume** [comment]
je n'ai pas ce problème
