### ISSUE TITLE
Afficher aires de span pour toutes les sources, comme dans l'octogris

### ISSUE THREAD

**Issue by DominicThibault** [GRIS-UdeM/ZirkOSC#19]
Les sliders de span (azimuth et elevation) contrôlent tous les sources en simultané alors que l'interface laisse croire que ce paramètre est individuel pour chaque source. Ça crée de la confusion 
- parce que les sliders de span se retrouvent dans la même section de les sliders de positionnement
- parce que lorsque l'on change une valeur de span, on ne vois la mise-à-jour que pour la source sélectionnée.

**Comment by vberthiaume** [comment]
Ouais bon point. Je pourrais faire comme dans l'octogris et faire que les aires de span soient affichées pour toutes les sources, qu'en dis-tu Robert?
