### ISSUE TITLE
Mouvement groupés - sources impossible à sélectionner

### ISSUE THREAD

**Issue by DominicThibault** [GRIS-UdeM/ZirkOSC#20]
Lorsqu'une source est déplacée dans un mouvement groupé et que son élévation se devient 0. (ou inférieur, si c'est possible), il devient alors impossible de reprendre le contrôle/sélectionner la source avec la souris.
<https://dl.dropboxusercontent.com/u/2295576/GRIS/ZirkOSC_3_0_0_GroupedMovement01.mov>

Si on se met en mode "Independant", il est possible de reprendre le contrôle de la source
<https://dl.dropboxusercontent.com/u/2295576/GRIS/ZirkOSC_3_0_0_GroupedMovement02.mov>

**Comment by vberthiaume** [comment]
Intéressant. J'était au courant qu'il était impossible de sélectionner les sources qui sortent du cercle, mais pas qu'Il était possible de les rattraper en mode indépendant. Les "débordements" de sources sont un problème mathématique qui m'a pris beaucoup de temps à résoudre. Je peux voir pour ajouter la possibilité de les rattraper en mode non-indépendant, mais il est possible que ça prenne plus d'effort qu'il est utile en ce moment.

**Comment by vberthiaume** [comment]
Je ne suis pas capable de récupérer les sources "débordantes" en mode indépendant; je pense que dans ton exemple c'est seulement que la source n'avait pas encore vraiment débordé. Je vais mettre les sources qui sortent du cercle en gris, et si jamais c'est vraiment un problème je me pencherai sur la question.
