### ISSUE TITLE
Source elevation à 90° change l'azimuth à 180°

### ISSUE THREAD

**Issue by DominicThibault** [GRIS-UdeM/ZirkOSC#21]
Lorsque l'on change l'élévation d'une source avec le slider et qu'on atteint 90°, son azimut est automatiquement changé à 180°. Ensuite de cela, lorsque l'on redescend l'élévation, l'azimut alterne entre 180° et -180°.
<https://dl.dropboxusercontent.com/u/2295576/GRIS/ZirkOSC_3_0_0_Circular02.mov>

**Comment by vberthiaume** [comment]
Ceci représente 2 bugs (donc devrait être 2 issues):
1- l'azimuth change à 180 automatiquement quand on dragge le slider d'élévation à 90°
2- l'azimuth alterne entre 180 et -180

Le premier est un bug assez important, le 2e assez minime.

**Comment by DominicThibault** [comment]
Même problème sur DP

**Comment by vberthiaume** [comment]
ceci est encore vrai si l'élévation est -180
