### ISSUE TITLE
movement près d'une élévation de 0

### ISSUE THREAD

**Issue by DominicThibault** [GRIS-UdeM/ZirkOSC#22]
Le mouvement groupé des sources fonctionne étrangement. 2 observations:
1) Si deux sources ont à peu près la élévation en périphérie (par exemple 0. et 5.), elles s'éloignent de plus en plus l'une de l'autre lorsqu'elles se rapprochent du centre
<https://dl.dropboxusercontent.com/u/2295576/GRIS/ZirkOSC_3_0_0_Circular01.mov>

2) Lorsque qu'une source est poussée vers une élévation de 0., si on réussit à la re-sélectionner, le mouvement groupé devient alors problématique:
<https://dl.dropboxusercontent.com/u/2295576/GRIS/ZirkOSC_3_0_0_Circular03.mov>

**Comment by vberthiaume** [comment]
Ceci représente 2 points séparés (svp un point par issue ;) ).
1) ceci est due à la forme du dome, une sphère, c'est donc complètement normal. 
2) étrange! je regarde ça
