### ISSUE TITLE
Mouvement groupé "Equal Azimuth" erroné

### ISSUE THREAD

**Issue by DominicThibault** [GRIS-UdeM/ZirkOSC#23]
Le mode "Equal Azimuth" ne semble pas fonctionner. Avec deux sources, ne devraient-elle pas se retrouver à l'opposé l'une de l'autre (180°)? Ce n'est pas le cas actuellement:
<https://dl.dropboxusercontent.com/u/2295576/GRIS/ZirkOSC_3_0_0_EqualAzimuth02.mov>

Aussi, lorsque l'on passe de "Independant" à "Equal Azimuth", on obtient un étrange mouvement des deux sources.
<https://dl.dropboxusercontent.com/u/2295576/GRIS/ZirkOSC_3_0_0_EqualAzimuth01.mov>
(La même chose survient avec le mode "Equal Elev+Azim")

**Comment by vberthiaume** [comment]
Je suis conscient des problèmes du genre dans reaper (est-ce que ça arrive dans les autres séquenceurs?). Est-ce que tu peux me décrire comment tu reproduit ce problème à partir d'un nouveau projet?
