### ISSUE TITLE
Problèmes avec azimuth inversé

### ISSUE THREAD

**Issue by DominicThibault** [GRIS-UdeM/ZirkOSC#24]
Alors, voici ce que j'observe avec le scaling en mode circulaire

Étape pour reproduire:
1) Charger une nouvelle session dans Reaper ou DP
2) Charger sur une piste ZirkOSC3
3) Nbr sources = 2
4) En mode "independant", déplacer les sources de telle sorte qu'elles aient des élévations différentes mais des azimuth semblables.
5) Déplacer la source la plus extérieur vers le centre jusqu'à ce que la source la plus intérieur dépasse le centre mais pas la source la plus extérieure.
6) Sélectionner la source qui a dépassé le centre et la bouger.
7) Re-sélectionner la source originale et la bouger. Noter que le scaling est alors inversé.

Est-ce dû au fait que la source dépasse le centre? Devrait-elle dépasser le centre?
<https://dl.dropboxusercontent.com/u/2295576/GRIS/ZirkOSC_3_0_0_Circular04.mov>

**Comment by vberthiaume** [comment]
ah oui, je vois. Ce qui se passe est que l'Azimuth de la source qui passe
par 0 devient "inversé", un status un peu spécial au niveau des maths
d'angles. Dans la prochaine version je vais mettre en rouge les sources
dont l'azimuth est inversé, on verra si ça vaut la peine de faire plus
après.

2015-07-24 13:51 GMT-04:00 Dominic Thibault <notifications@github.com>:
