### ISSUE TITLE
REAPER - Menu déroulant "Mouvement groupé" - État initial non enregistré

### ISSUE THREAD

**Issue by DominicThibault** [GRIS-UdeM/ZirkOSC#26]
Lorsque l'on enregistre l'automation de ZirkOSC dans Reaper, l'état du menu déroulant "Mouvement groupé" n'est pas enregistré en début de lecture de la séquence. Cela peut être problématique si la valeur du menu est changée alors que la piste n'est pas en mode "write".

1) Ouvrir Reaper
2) Créer une piste
3) Charger ZirkOSC3, changer "nbr sources" = 8 et "1st source ID"=1
4) Changer la valeur du menu déroulant à "Circular"
5) Armer l'automation de la piste (mode "write")
6) Enregistrer un mouvement des sources alors que la séquence roule
7) Arrêter la séquence mais rester en mode "write"
8) Changer la valeur du menu déroulant à "Equal elevation". Une première automation est écrite pour le paramètre "Move_Constraint".

L'état du menu déroulant a donc été sauvegardé en "Equal Elevation" même si le mouvement des sources était fait en "Circular". Lorsque cette automation sera rejouée, le mouvement groupé sera donc erroné.

Idéalement, une automation du paramètre "Move_Constraint" est écrite à chaque fois que la séquence démarre avec le mode "write" et que la valeur  de "Move_Constraint" a changé.

**Comment by vberthiaume** [comment]
Très "intéressant" comme problème... j'ai du travailler pas mal pour forcer une écriture de l'automation, et ça marche pas terrible. Le fix que j'ai trouvé est qu'il faut constamment écrire l'automation du mode de mouvement... et ça ne marche que dans reaper pour l'instant.

**Comment by DominicThibault** [comment]
Ça semble marcher comme solution sur Reaper...
