### ISSUE TITLE
Fréquence de mise à jour des positions de sources groupées

### ISSUE THREAD

**Issue by DominicThibault** [GRIS-UdeM/ZirkOSC#31]
REAPER
Lorsque l'on rejoue une automation, il semble que la précision des mouvements groupés soit problématique en raison du "refresh rate" des sources groupées à la source principale. La source principale bouge de façon fluide alors que toutes les autres sources sont mises à jour avec un décalage.

Lors de l'enregistrement, ce décalage n'est pourtant pas apparent.

Étapes:
1) Créer une nouvelle session Reaper
2) Charger le plugin
3) Changer le nombre de source à 8
4) Mettre la piste en "write"
5) Choisir, par exemple, le mouvement groupé "Circular" dans le menu déroulant.
6) Enregistrer une trajectoire circulaire de 5 secondes pour 4 cycles
7) Se mettre en mode "read"
8) Rejouer la trajectoire pour constater le "lag" des sources liées.

**Comment by DominicThibault** [comment]
Le même problème est aussi présent dans DP8, quoi que moi perceptible.

**Comment by DominicThibault** [comment]
Bonne question. J'imagine que c'est surtout un question de perception. Est-ce que des sauts dans l'espace à tous les 100ms c'est perceptible? Ça doit dépendre de la vitesse du mouvement. Fais-tu une interpolation entre les positions?

**Comment by vberthiaume** [comment]
Non, je ne fais pas d'interpolation, comment ça marcherait? Si j'ai une
position1 au temp t, et une position2 au temps t+100ms, quelle
interpolation y-a-t'il à faire? J'imagine que je pourrais faire un genre de
délai, style si la position2 est à une position trop loin de la position1,
je mets la source à une position 1.5 (entre les 2) et au temps t+200ms là
je mets la source à position2? Si on fait ça on ne respecte pas la
trajectoire qu'on avait et on pourrait avoir des gros délais qui
s'additionnent. Mieux vaudrait ajuster le taux de rafraichissement (ou
laisser l'utilisateur le faire) à une valeur convenable pour avoir une
performance ET de l'audio qui ont de l'allure...

2015-08-04 15:40 GMT-04:00 Dominic Thibault <notifications@github.com>:

**Comment by DominicThibault** [comment]
Je comprend ton interrogation.

Par interpolation, je voulais dire que, connaissant le taux de rafraîchissement (100ms), on peut faire une interpolation linéaire de 100 ms entre les 2 position. Mais, en effet, cela créera un délai de 100 ms puisqu'on ne connaît pas la position2 avant qu'elle soit lu.

Faudrait tester un refresh rate un peu plus bas.

Question: à quelle fréquence envoie-t-on des messages OSC au Zirkonium?

**Comment by vberthiaume** [comment]
On envoi l'OSC en même temps qu'on met à jour la position des sources
non-sélectionnées (c'est dans le même thread). Dans la version 3.0.3,
j'avais diminué le délai à 75ms, est-ce que ça fait une différence?

2015-08-06 14:21 GMT-04:00 Dominic Thibault <notifications@github.com>:
