### ISSUE TITLE
Saut dans la séquence ne met à jour que la position de la source enregistrée

### ISSUE THREAD

**Issue by DominicThibault** [GRIS-UdeM/ZirkOSC#32]
Lorsque l'on fait un saut dans la séquence (par exemple, faire passer le curseur de lecture de la mesure 3 à 8 instantanément), seule la position de la source qui est automatisée est mise à jour. Les sources liées par un mouvement groupé et/ou une trajectoire ne sont pas mises à jour.

Étapes:
1) Créer une nouvelle session Reaper ou DP8
2) Charger le plugin
3) Changer le nombre de source à 8
4) Choisir le mouvement groupé "Circular" dans le menu déroulant.
5) Créer une automation soit en bougeant directement la source ou en enregistrant une trajectoire
6) Lorsque la séquence est en "pause", se déplacer dans la séquence en cliquant divers endroits dans la séquence.

Lorsque la lecture redémarre, la position des autres sources est remise à jour mais je crois que cela peut p-e causer des glitchs ou clics en début de lecture.

Problème identique testé dans Reaper et DP8.

**Comment by vberthiaume** [comment]
Mmm. Il serait important de vérifier si l'audio est affecté, parce que de mon coté ce comportement découle directement du fait qu'on enregistre l'automation sur une seule source. Je pourrais faire que les sources non-sélectionnées vérifient constamment la position de la source sélectionnée, mais ça causerait des lags de performance importants, et on perdrait l'avantage qu'on a à utiliser l'automation d'une seule source.

**Comment by DominicThibault** [comment]
Question: Pourquoi est-ce que la séquence doit rouler pour mettre à jour les autres sources?

Quand on déplace avec la souris des sources qui sont liées mais pas automatisées, toutes les sources suivent même si la séquence est arrêtée.

Alors, pourquoi, lorsque c'est une automation, la position des autres sources n'est pas mise à jour?

**Comment by vberthiaume** [comment]
Pour être capable de détecter les sauts, il faudrait que le code pour les
sources non-sélectionnée roule constamment, ce qui prends pas mal de jus,
et qui je pense rends l'écriture d'automations aussi "glitchy" que
lorsqu'on enregistrait l'automation sur toutes les sources en parallèle...
Je vais faire quelques tests pour vérifier.

2015-08-06 14:16 GMT-04:00 Dominic Thibault <notifications@github.com>:
