### ISSUE TITLE
REAPER - Paramètres figés lorsqu'une automation a été enregistrée

### ISSUE THREAD

**Issue by DominicThibault** [GRIS-UdeM/ZirkOSC#33]
Lorsqu'un mouvement a été enregistré par automation, il devient impossible de changer plusieurs paramètres du plugins. Voici lesquels:
- Nbr sources
- 1st source ID
- ZKM OSC port
- Menu déroulant des mouvement groupés
- Les boîtes à chiffre du panneau de trajectoires

Ce problème n'est observable que dans Reaper. Dans DP8, pas de problème.

Étapes:
1) Créer une nouvelle session Reaper
2) Charger le plugin sur une piste
3) Changer le nombre de source à 8
4) Choisir le mouvement groupé "Circular" dans le menu déroulant.
5) Enregistrer une automation directement en bougeant une source ou en enregistrant une trajectoire.
6) Tenter de changer un des paramètres indiqué plus haut, par exemple, la boîte à chiffre de durée d'une trajectoire. Notez que le chiffre indiqué ne peut être remplacé.

Ceci semble dû au fait que ces valeurs sont écrit en automation, d'une manière ou d'une autre.

**Comment by vberthiaume** [comment]
voir #34
