### ISSUE TITLE
REAPER - Source imposible à bouger lorsque contrôlée par une automation.

### ISSUE THREAD

**Issue by DominicThibault** [GRIS-UdeM/ZirkOSC#34]
Lorsqu'une source est contrôlée par une automation, il devient impossible de changer sa position avec la souris dans l'interface graphique. Ce problème n'est observable que dans Reaper. Dans DP8, on peut déplacer la source même si elle est liée à une automation (ce qui est le comportement normal). 

Étapes:
1) Créer une nouvelle session Reaper
2) Charger le plugin sur une piste
3) Changer le nombre de source à 8
4) Choisir le mouvement groupé "Circular" dans le menu déroulant.
5) Enregistrer une automation directement en bougeant une source ou en enregistrant une trajectoire.
6) Tenter de changer la position de la source automatisée. Notez qu'il est impossible de la changer alors que les autres sources sont contrôlables. 

Ceci est problématique pour les modes d'écriture d'automation "Touch" ou "Latch".

**Comment by vberthiaume** [comment]
Oui, c'est effectivement un problème important... mais je pense qu'on va devoir vivre avec, à moins qu'il y ait des options qu'on puisse changer dans reaper? Il m'est impossible "d'overrider" ce que les séquenceurs font sur les paramètres.

**Comment by DominicThibault** [comment]
J'ai fait une recherche dans les préférences de Reaper et n'ai rien trouvé à ce sujet.

Je sais que les modes "Read" et "Trim/Read" créent beaucoup de confusion dans Reaper.  

Après investigation, je suis d'accord avec toi, il n'y a pas grand chose à faire pour cet issue.
