### ISSUE TITLE
Set End Point

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ZirkOSC#36]
En essayant de faire une trajectoire qui part de Azim 88 Elev 79 vers Azim 90 et Elev 23, ça déborde largement du cercle avec une source stéréo:
https://www.dropbox.com/s/q67rndktou0kr2n/Set%20end%20point%20Spiral%20Stereo.mov?dl=0
Avec une source octophonique, en partant de l'extérieur vers l'intérieur, cela part du bon endroit, oscille autour du point d'arrivée (end point) et finalement repart vers le point de départ;
https://www.dropbox.com/s/ilb1aq11ivmv48t/Set%20end%20point%20Spiral%20Octo.mov?dl=0

**Comment by vberthiaume** [comment]
Ces 2 trajectoires m'apparaissent correctes... C'est un peu difficile d'expliquer en texte, mais le premier tour de spirale est entre le point de départ et 2x la distance au point d'arrivée. Ça m'a pris vraiment tout mon petit change mathématique pour faire cette spirale, je ne sais pas combien de temps ça me prendrait pour faire une spirale asymétrique, qui reste toujours dans le centre du cercle. Par contre, au cours de mes "expérimentations", j'ai fait une spirale étirée (un peu comme une tornade?), qui elle reste toujours dans le cercle. J'ai aussi fait un pendule avec de l'amortissement (l'amplitude diminue avec chaque cycle). Je pensais mettre ces trajectoires dans une prochaine version.
