### ISSUE TITLE
First Source ID ne fonctionne plus

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ZirkOSC#37]
Il n'y a plus que les Sources 1 et 2 en stéréo  et 1 à 8 en octo qui sont disponibles et cela par défaut. Aucune autre valeur n'est prise en compote dans cette boîte.
DP9, Logic X, Reaper 4

**Comment by vberthiaume** [comment]
c'est réglé, mais avec la nouvelle façon d'afficher les numéros de source (volée à l'Octogris), on ne peut afficher que 2 chiffres... est-ce que 99 sources sont suffisantes? Surement pas. Alors on a le choix: option 1) essayer de faire rentrer 3 chiffres dans les sources, potentiellement en mettant les sources plus grandes, ou option 2) sortir les numéros des sources, comme c'était avant. Je fais des tests avec option 1 pour voir ce que ça donne ?

**Comment by Normandeau** [comment]
Je crois que 99 sources est suffisant. N'oublions pas que ce qu'on spatialise avec le ZirkOSC, ce sont des fichiers audio «stems», c'est à dire des fichiers finaux en termes de compositions. 99 pistes audio de spatialisation pour une pièce, c'est vraiment beaucoup. Ma pièce la plus complexe à ce jour contient 40 pistes de diffusion.
