### ISSUE TITLE
oscillation sur les xy en mode non-independant

### ISSUE THREAD

**Issue by vberthiaume** [GRIS-UdeM/ZirkOSC#42]

**Comment by vberthiaume** [comment]
need to test on other machines

**Comment by vberthiaume** [comment]
gris_dev: cercle 10 sec, une seule source, independent
* dp: fine
* reaper: oscillation
* logic: oscillation

**Comment by vberthiaume** [comment]
l'oscillation a été introduite entre 220 et 221, avec l'utilisation des coordonnées XY
* 2.2.3 oscille
* 2.2.2 oui
* 2.2.1 oui
* 2.2.0 non 
* 2.1.1 pas oscillation

**Comment by vberthiaume** [comment]
see here: http://stackoverflow.com/questions/2785601/c-numerical-truncation-error

**Comment by vberthiaume** [comment]
le fait que le pendule n'oscille pas lors qu'il est seulement sur un axe (x ou y) semble indiquer que le problème est lorsqu'on a 2 paramêtres qui encodent la trajectoire.

**Comment by vberthiaume** [comment]
J'en ai parlé avec @ludoviclaffineur et il confirme que Logic a des problèmes avec les automations, voir http://www.logicprohelp.com/forum/viewtopic.php?f=42&t=110712

**Comment by Normandeau** [comment]
Quand on se compare on se console!
Je n'ai aucun autre plugin qui possède des trajectoires d'automation telles que celles que nous avons introduites dans Octogris et ZirkOSC. Même le nouveau GRMSpaces n'écrit pas ses trajectoires dans l'automation de piste. La trajectoire est écrite dans le plugin lui-même.
Ma question du jour était: est-ce que les autres plugins ont des trajectoires aussi jaggy que ce que l'on trouve avec nos plugiciels?
Voici la réponse, certes fragmentaire mais utile au débat.
Les tests ont été faits avec GRMSpaceFilter en écrivant des trajectoires de cercle manuellement.

DP9
Dans DP on peut ajuster la résolution de l'automation. Ici deux courbes, une à 100ms l'autre à 10ms. On constate qu'il n'y a pas une grande différence entre les deux et que l'écriture par paliers demeure une constante:

![dp9 spacefilter 100ms-10ms](https://cloud.githubusercontent.com/assets/8959779/9982905/96634a66-5fb9-11e5-8035-545f38e0fcf6.jpg)

Dans Logic, j'ai utilisé la résolution normale et ensuite la résolution Sample Accurate. Deux images valent pas mal de mots. En fait, le résultat est tout simplement catastrophique:

![logic spacefilter normal](https://cloud.githubusercontent.com/assets/8959779/9982907/b4fef7c2-5fb9-11e5-9c60-8363273cb6f2.jpg)

![logic spacefilter sampleaccurate](https://cloud.githubusercontent.com/assets/8959779/9982914/bf82e3fc-5fb9-11e5-94b0-48f85c67466e.jpg)

Enfin dans Reaper, dans lequel, à ma connaissance, il n'y a pas de réglages de précision dans l'écriture de l'automation, on obtient aussi un résultat désastreux, au point où la trajectoire repart dans le sens contraire à certains moments:

![reaper spacefilter](https://cloud.githubusercontent.com/assets/8959779/9982920/dda5e140-5fb9-11e5-932a-b04cb08021c0.jpg)

**Comment by Normandeau** [comment]
La limitation dans Logic ne touche que les fichiers octophoniques. La plupart ds gens ne vont utiliser que des fichiers mono ou stéréo.
En discutant avec l'un de mes étudiants qui a fait deux pièces pour dôme l'an dernier avec Logic, David Ledoux, je me suis rendu compte de cette nuance, qui permet une plus grande flexibilité, que celle d'utiliser des fichiers octophoniques, car cela implique un niveau de composition déjà plus avancé. Je crois qu'il faut continuer à surveiller de près Logic, d'autant plus que nous avons un nouveau membre au GRIS, Alexis, dont c'est l'outil de travail principal et qui travaille régulièrement en multiphonie. The battle continues... (soupir!).
