### ISSUE TITLE
Random et independant: une seule source

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ZirkOSC#5]
Dans la trajectoire Random, si on est en mode Independant, on n'a que la source 1 qui est affectée par la trajectoire. Si on compare la même trajectoire dans Octogris2, on notera que ce dernier propose une source (au choix) ou All sources. On remarque aussi d'ailleurs que cette trajectoire bypasse le mode de groupement. Même en mode Circular Fully Fixed, la trajectoire Random est en mode Independant. Question: est-ce une erreur de conception? Je pense qu'on devrait être conséquent. Le mode groupé devrait être prioritaire, donc si on est en mode Circular Fully Fixed, la trajectoire Random devrait s'exercer sur toutes les sources de la même manière, comme c'est le cas actuellement dans ZirkOSC2. Ce sera alors à l'utilisateur à «libérer» les sources, en choisissant le mode Independant,  la trajectoire Random s'appliquerait alors à toutes les sources. Doit-on ajouter l'option d'Octogris avec le menu déroulant Source Nb et All sources. Pourquoi pas? On serait là aussi conséquent.

**Comment by vberthiaume** [comment]
Avec les automations à source unique, les trajectoires suivent obligatoirement les contraintes de mouvement, donc cette partie est réglée. Pour ce qui est du menu déroulant... je ne suis pas sur que ça fasse du sens de le mettre dans le ZirkOSC, parce qu'on a le concept de la source sélectionnée. Si on veut bouger toutes les sources, on se met en mode non-indépendant, et si on veut bouger une seule source, on la sélectionne et on se met en mode indépendant. Ce menu déroulant fait du sens dans l'Octogris parce qu'on a pas ce concept de source sélectionnée; mais le mettre dans ZirkOSC serait mêlant parce qu'on aurait 2 contrôles qui pourraient se contredire, soit le menu déroulant et la source sélectionnée. Est-ce que ça fait du sens?

**Comment by vberthiaume** [comment]
semble fonctionner sauf pour la position finale qui n'est pas la position initiale... peut-être du au "jitter" des sources non-sélectionnées en xy
