### ISSUE TITLE
Oscillations OSC dans DP

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ZirkOSC#53]
DP9
Oscillation
Aussitôt qu'on ouvre une instance de ZirkOSC3, que l'OSC de celui-ci est actif (valeur par défaut) et qu'on change la position de la Source 1, on a une oscillation de celle-ci dans le Zirkonium.
Voir tze film:
https://www.dropbox.com/s/oy1xirxvnpirge5/Oscillation%20OSC.mov?dl=0
On constate le même comportement dans ZirkOSC2 (2.2.2), ce qui est étrange, car on n'a jamais eu cela auparavant (et le Zirkonium n'a pas changé de version depuis un an).
Sources asymétriques
De plus, quand on sélectionne une source autre que la source 1, en mode Equal Elev + Azim, le rapport entre toutes les sources est modifié et celles-ci deviennent toutes asymétriques.
Voir tze film no 2:
https://www.dropbox.com/s/4qc7h9n1582mo5c/Oscillation%20OSC%20Positions.mov?dl=0

Logic 10
Oscillation
On n'observe pas le même comportement ici. La Source 1 est stable par défaut. Cependant on observe une oscillation de ce type si on ouvre un second ZirkOSC3 avec les mêmes valeurs de numéros dans une position différente. Mais cela est le comportement attendu puisque le Zirkonium reçoit deux coordonnées OSC différentes pour chacune ds sources.
Donc dans DP, c'est comme si celui-ci envoyait deux valeurs OSC pour la Source 1: la valeur par défaut, à savoir -179.99 et la valeur réelle de la position de la Source 1 après qu'elle ait été déplacée. Et le Zirkonium oscille entre les deux.
Asymétrie
Même comportement des sources que dans DP.

Reaper 5
Oscillation
Même commentaire que pour Logic.
Asymétrie
Même comportement des sources que dans DP et Logic.

**Comment by vberthiaume** [comment]
Je vois ici 2 bogues: 

1) oscillation dans le zirkonium avec DP. 
2) en mode equal azim+élév, déplacer une source autre que la première source sélectionnée change l'azimuth des sources d'une façon asymétrique. 

Le point 2) est un vrai bogue, et je vais faire une autre issue pour, mais je pense que le point 1) est un bogue interne de DP. J'avais eu ce problème dans le studio avec toi Robert, je sais pas si tu te souviens? Dans mon cas, c'est comme si DP avait gardé en mémoire une ancienne copie du zirkosc, qui continuait d'envoyer des messages osc en parallèle avec le "vrai" zirkosc de ma piste! Je n'avais plus ce problème quand j'ai créé un nouveau projet de test. Ça a réglé aussi un bogue que j'avais depuis vraiment vraiment longtemps; il y avait également une instance d'octogris qui était restée en mémoire dans mon projet et ça me faisait des erreurs quand je débuggais un projet DP dans xcode. Tout ça est parti quand j'ai créé un nouveau projet, mais peut-être qu'il suffirait d'effacer la track défectueuse? Je ne sais pas si ça vaudrait la peine de mentionner ce bogue dans le manuel?

**Comment by Normandeau** [comment]
1) oscillation dans le zirkonium avec DP. 
Ok je vais vérifier à nouveau. Je n'ai aps vider les caches cette fois-ci. Pure paresse! Ça prend quand même environ 15 minutes pour vider et réinstaller les caches de tout le monde à chaque fois. Je vous tient au courant.
Je vais vérifier avec la version 8 aussi.

**Comment by vberthiaume** [comment]
je n'ai pas eu à vider les caches, juste prendre un nouveau projet!

2015-09-21 12:46 GMT-04:00 Robert Normandeau <notifications@github.com>:
