### ISSUE TITLE
Fin de ZirkOSC pour Logic?

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ZirkOSC#55]
En réalisant une série de tests un peu plus complexes pour vérifier l'instabilité et les oscillations dans Logic, je viens seulement de me rendre compte que Logic a une limitation majeure: on ne peut pas utiliser plus d'un seul groupe de sorties en 7.1. Autrement dit, nous sommes limités aux 8 sorties décrites dans le format Surround des Preferences. En utilisant Jack, nous sommes donc limités par exemple aux sorties 1 à 8 (valeurs par défaut). Lorsqu'on place une seconde instance de ZirkOSC3, avec une attribution des sources de 9 à 16 par exemple, le Zirkonium réagit en conséquence, c'est à dire que les sources bougent dans l’espace (autrement dit le code OSC est envoyé correctement)... mais pas le son! Car le son arrive toujours au Zirkonium, via Jack par les sorties 1 à 8.
Une recherche rapide sur différents forum confirme la chose.
Fin de ZirkOSC pour Logic?
En fait je crois qu’en posant la question, je viens de trouver la réponse: si les pistes sont toutes en stéréo cela ne pose pas de problème, car Logic permet de faire sortir les pistes sur autant de sorties  disponibles sur l'interface choisie. Mais ce choix n'est possible que pour les assignations mono ou stéréo, par pour les Surround.
Donc ce n'est pas tout à fait terminé, mais ça devient pas mal moins prioritaire.

**Comment by vberthiaume** [comment]
mmm j'avoue que c'est une grosse limitation, qui ajoutée aux problèmes d'automations que nous avions déjà, rend Logic un choix vraiment sous-optimal pour travailler avec le ZirkOSC! Donc est-ce qu'on décide officiellement de ne rien faire pour l'issue #42, qui affecte principalement Logic?

**Comment by Normandeau** [comment]
La limitation dans Logic ne touche que les fichiers octophoniques. La plupart ds gens ne vont utiliser que des fichiers mono ou stéréo.
En discutant avec l'un de mes étudiants qui a fait deux pièces pour dôme l'an dernier avec Logic, David Ledoux, je me suis rendu compte de cette nuance, qui permet une plus grande flexibilité, que celle d'utiliser des fichiers octophoniques, car cela implique un niveau de composition déjà plus avancé. Je crois qu'il faut continuer à surveiller de près Logic, d'autant plus que nous avons un nouveau membre au GRIS, Alexis, dont c'est l'outil de travail principal et qui travaille régulièrement en multiphonie. The battle continues... (soupir!).
Je peux ajouter que l'utilisation de fichiers octophoniques par des utilisateurs sera probablement une situation exceptionnelle. On le mentionnera dans la guide de ZirkOSC, mais nous devons continuer à tester Logic comme auparavant. Désolé de la fausse alerte!

**Comment by vberthiaume** [comment]
message bien recu, voir ici pour le problème à régler (ou pas): https://github.com/GRIS-UdeM/ZirkOSC/issues/42
