### ISSUE TITLE
Asymétrie des azimuth

### ISSUE THREAD

**Issue by vberthiaume** [GRIS-UdeM/ZirkOSC#56]
En mode equal azim+elev, déplacer une source autre que la première source sélectionnée change l'azimuth des sources d'une façon asymétrique.

**Comment by Normandeau** [comment]
Ce problème n'est pas réglé. Il apparaît dans les trois séquenceurs. DP et Reaper sont les pires. Logic est plutôt stable. La situation: bouger un groupe octophonique manuellement en mode Equal Elev + Azimut en saisissant des sources différentes. Peu à peu, les sources se désolidarisent et forment une figure asymétrique.
DP:
![dp desolidarisation des sources](https://cloud.githubusercontent.com/assets/8959779/10223745/98d96204-6828-11e5-968e-428282eb53aa.jpg)

Logic:
![logic desolidarisation des sources](https://cloud.githubusercontent.com/assets/8959779/10223751/a52bb232-6828-11e5-94f0-3b7ec9591358.jpg)

Reaper:
![reaper desolidarisation des sources](https://cloud.githubusercontent.com/assets/8959779/10223758/adaa6e4e-6828-11e5-8a48-c75dba6202cd.jpg)

J'ai testé l'enregistrement de l'automation afin de vérifier si cette désolidarisation s’enregistrait. En fait, ce qui arrive, c'est que lorsqu'on choisit une source autre que la Source 1 — celle qui devrait dicter le chemin aux autres donc — on retombe dans le mode Independent, dans le sens où chacune des sources se met à écrire sa propre automation au fur et à mesure qu'elle est sélectionnée:
![dp ecriture independante](https://cloud.githubusercontent.com/assets/8959779/10224179/cb67d6ae-682a-11e5-9ccb-e3e5e4bf6688.jpg)

Alors là c'est vraiment la confusion car la Source 1 essaie de dicter le chemin aux autres, mais les autres ont leur propre autonomie.
Il faudrait s'assurer que lorsqu'on est en mode Link Movement, quelque soit le mode choisi, même en sélectionnant une source autre que la Source 1, qu'il n'y ait que celle-ci qui puisse s'écrire.

**Comment by vberthiaume** [comment]
Ah je vois. Si c'est comme pour moi, le problème arrive seulement lorsqu'on écrit l'automation. Si on parle bien de la même chose, c'est un problème différent, que j'avais souligné dans une question il y a un petit bout: https://github.com/GRIS-UdeM/Octogris/issues/54. 

Comme je l'avais mentionné, je peux essayer de contourner le problème, mais c'est vraiment pas évident que ça va être stable, étant donné qu'on doit contourner les directives du séquenceur. 

Je ne pense pas qu'il soit possible d'empêcher l'écriture d'automation (je ne peux pas empêcher le séquenceur de lire dans le plugin), mais je peux essayer d'empêcher la lecture d'automation (ie, ignorer les positions que le séquenceur donne au plugin) pour les sources non-sélectionnées, lorsque nous sommes en mode non-indépendant. C'est assez tricky par contre, donc c'est pas sur que ça va fonctionner et je ne suis pas sur de combien de temps ça va me prendre. Je me demande si ce n'est pas mieux pour l'instant de mettre cette limitation dans le manuel, histoire d'avoir une version à publier? Ou je peux commencer à travailler là dessus et on verra comment ça avance?

**Comment by Normandeau** [comment]
Vincent,

Ce que j’ai remarqué aujourd’hui c’est que cette désolidarisation des sources se produit également quand on fait juste jouer avec le ZirkOSC, sans rien enregistrer de l’automation.
Les images que j’ai capturées ont été faites sans automation.
Juste en jouant avec les sources et en capturant l’asymétrie graduelle qui s’installe.
C’est encore pire cependant lorsqu’on enregistre l’automation.

Millas oui, je suis en train de repasser à travers le manuel, et je vais très clairement indiquer cette limitation.
On pourra publier cette version avec cette mise en garde (ainsi qu’avec toutes les autres mises en garde).

Dès que j’ai terminé le manuel, je vais le mettre sur Github.

Ensuite on pourra ouvrir le compte Source Forge pour ZirkOSC3.

> Le 2015-10-01 à 11:25, Vincent Berthiaume <notifications@github.com> a écrit :
> 
> Ah je vois. Si c'est comme pour moi, le problème arrive seulement lorsqu'on écrit l'automation. Si on parle bien de la même chose, c'est un problème différent, que j'avais souligné dans une question il y a un petit bout: GRIS-UdeM/Octogris#54 <https://github.com/GRIS-UdeM/Octogris/issues/54>.
> 
> Comme je l'avais mentionné, je peux essayer de contourner le problème, mais c'est vraiment pas évident que ça va être stable, étant donné qu'on doit contourner les directives du séquenceur.
> 
> Je ne pense pas qu'il soit possible d'empêcher l'écriture d'automation (je ne peux pas empêcher le séquenceur de lire dans le plugin), mais je peux essayer d'empêcher la lecture d'automation (ie, ignorer les positions que le séquenceur donne au plugin) pour les sources non-sélectionnées, lorsque nous sommes en mode non-indépendant. C'est assez tricky par contre, donc c'est pas sur que ça va fonctionner et je ne suis pas sur de combien de temps ça va me prendre. Je me demande si ce n'est pas mieux pour l'instant de mettre cette limitation dans le manuel, histoire d'avoir une version à publier? Ou je peux commencer à travailler là dessus et on verra comment ça avance?
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/GRIS-UdeM/ZirkOSC/issues/56#issuecomment-144761920>.
> 

Bonne journée

•••••••••••••••••••••••••••••••••••••••
Robert Normandeau
Vice-doyen aux études en création et technologie
Professeur titulaire de composition électroacoustique
Faculté de musique, B-660, 343-6111 poste 3486
Université de Montréal
http://www.musique.umontreal.ca/personnel/normandeau_r.html

**Comment by vberthiaume** [comment]
Mmm bizarre, de mon coté je ne suis pas capable de reproduire le problème sans écrire d'automations. Tu est en mode read? Et est-ce que tu fait jouer le séquenceur en même temps? S'il n'implique pas d'automations, ce problème devrait définitivement être réglable. Peux tu me faire un vidéo rapide?

**Comment by Normandeau** [comment]
Voici la vidéo:
https://www.dropbox.com/s/5utvsgspkwf0727/Sources%20d%C3%A9solidaris%C3%A9es.mov?dl=0

**Comment by vberthiaume** [comment]
ok je vois, c'est de très petites erreurs qui s'accumulent après beaucoup
de mouvements rapides. Je peux régler ça en forçant une ré-évaluation des
positions à chaque sélection de source. Ça va prendre un petit peu plus de
jus mais ça ne devrait pas paraître. On va quand même avoir le problème
avec les automations qui se contredisent, ce qui devrait être dans le
manuel ;)

On Thu, Oct 1, 2015 at 12:04 PM, Robert Normandeau <notifications@github.com

**Comment by Normandeau** [comment]
> Le 2015-10-01 à 12:08, Vincent Berthiaume <notifications@github.com> a écrit :
> 
> ok je vois, c'est de très petites erreurs qui s'accumulent après beaucoup
> de mouvements rapides. Je peux régler ça en forçant une ré-évaluation des
> positions à chaque sélection de source. Ça va prendre un petit peu plus de
> jus mais ça ne devrait pas paraître.

Parfait.
Tu remarqueras que les erreurs sont plus évidentes lorsqu’on est très près du centre, ou qu’on traverse le centre.

> On va quand même avoir le problème
> avec les automations qui se contredisent, ce qui devrait être dans le
> manuel ;)

Oui j’ai déjà mentionné la chose dans le nouveau manuel.


Bonne journée

•••••••••••••••••••••••••••••••••••••••
Robert Normandeau
Vice-doyen aux études en création et technologie
Professeur titulaire de composition électroacoustique
Faculté de musique, B-660, 343-6111 poste 3486
Université de Montréal
http://www.musique.umontreal.ca/personnel/normandeau_r.html

**Comment by vberthiaume** [comment]
Oui, les erreurs proviennent de calculs aux limites des fonctions sinusoïdales, ie, au centre et au bord du dome. Dans la prochaine version, les sources vont se repositioner automatiquement lorsqu'on clique sur une source, ou sur n'importe quoi qui provoque un rafraichissement de l'interface. Je ne peux pas empêcher complètement les erreurs de calcul mais je peux les faire disparaître une fois de temps en temps ;)
