### ISSUE TITLE
Pendulum ne marche plus

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ZirkOSC#62]
Les deux Pendulum se comportent comme la Spiral.

**Comment by vberthiaume** [comment]
Tout est fonctionnel chez moi, est-ce que par hasard ton champs "turns" est
mis à 1? Je m'en sers comme paramêtre de déviation... J'imagine que je
pourrais le forcer à 0 par défaut pour le pendule?

Dans le fond, je réalise que maintenant avec le paramêtre "turns", la
spirale et le pendule sont exactement identiques! Dans le sens qu'un
pendule avec turns = 1 est une spirale et une spirale avec turns = 0 est un
pendule. Je pourrais enlever l'option pendulum? On aurait encore le damped
pendulum, et la possibilité de faire un non-damped pendulum en faisant une
spirale à 0 tours.

**Comment by Normandeau** [comment]
Vincent,
Je crois que les notions de pendule et de spirale sont vraiment très différentes dans l’esprit de l’utilisateur moyen (comme moi…). On peut toujours essayer de les convaincre que mathématiquement, de la manière dont nous avons intégré les paramètres, c’est pareil, mais je ne crois pas que ce soit une bonne approche.
Je vois ici plusieurs problèmes.
1) Le pendule n’en est plus un
Le vrai pendule, dans la vie de tous les jours, est celui qui parcourt toute la distance déterminée par un point de déséquilibre. Dans ZirkOSC, le pendule ne parcourt que la moitié de cette distance, du bord extérieur au centre, alors qu’il devrait aller d’un bord extérieur à l’opposé, tout en passant par le centre. Il faut déjà corriger cela. Le vrai pendule c’est celui d’Octogris avec la fonction Crossover. Si on veut lui faire parcourir la moitié du diamètre, c'est cette valeur qu'il faudra entrer, mais par défaut, c'est le diamètre complet qui doit être parcouru.

2) La fonction Turns est à travailler.
On l'a conçu comme une déviation angulaire de la trajectoire à l'origine.
Or cette déviation ne s’établit que pendant la durée du Turns et non pas pendant celle du pendule.
En effet, à l’heure actuelle le pendule revient à sa position de départ après la fin du Turns, même si la durée de la trajectoire du pendule n'est pas complétée. Donc si celui-ci est réglé à 0.5, le pendule, qui déjà ne parcourt que la moitié du diamètre, ne le fait plus que dans une moitié de la sphère! Ça fait beaucoup de moitiés! Avec en plus des sauts au point de départ.
Voir le film ici:
https://www.dropbox.com/s/43pz3aydryuakf2/Pendule.mov?dl=0

3. Le Set End point est… incompréhensible?
En tout cas, moi je n’y arrive pas intuitivement.
J’ai beau essayer, les valeurs n’entrent pas, et peu importe les valeurs que j’y met, ça ne change rien à la trajectoire.
Il faut que ça soit plus naturel.

**Comment by vberthiaume** [comment]
Bonjour Robert,

Ça vaudrait peut-être la peine de parler de vive voix pour qu'on regarde
les nouvelles fonctionnalités des trajectoires, mais rapidement:

1) le pendule va au milieu du dôme parce que le end point par défaut est le
milieu du dôme.
2) je ne suis pas certain de comprendre ce que tu veux dire par la "durée"
du turns. Turns n'est pas une mesure angulaire, c'est un nombre de tours de
déviations, qui s'applique tout au long de la trajectoire.  Si on entre .5,
le pendule va faire un demi-tout durant la trajectoire. 0.1 serait un 10e
de tour, etc
3) il faudrait qu'on regarde la fonction set end point ensemble, pour qu'on
voit ce qui n'est pas intuitif...

Vincent

2015-10-02 13:43 GMT-04:00 Robert Normandeau <notifications@github.com>:

**Comment by Normandeau** [comment]
Ok, il faudrait trouver un autre moment que le mercredi qui est ma journée la plus occupée à la fac (de 9h à 19h). On peut se voir chez moi aussi, ce qui est peut-être plus pratique, pour un rv d'une heure ou quelque, que d'aller à la fac. En plus, le studio de la fac est vraiment très occupé ce trimestre!
Par exemple je me rends compte que le Damped Pendulum fait ce que j'attends du Pendulum. Pourquoi une différence entre les deux avec les mêmes réglages?
Et puis j'ai beau essayer, quelque soit les réglages du Pendulum, je n'arrive jamais à lui faire traverser le zénith.
Pas nécessaire de répondre ici, on le fera de vive voix, mais c'est une situation plutôt frustrante.
