### ISSUE TITLE
Désolidarisation avec le pendule

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ZirkOSC#76]
DP, une piste octophonique, un Pendulum, Clockwise, Return de 12 sec répété 4 fois
Deviation de 360˚ et dampening de 0.5
La source 1 se désolidarise progressivement des autres. Elle prend de l'avance sur les autres, autant en Elevation qu'en Azimuth..
Voir le film:
https://www.dropbox.com/s/ze37t0kzaprz79n/D%C3%A9calage%20Dampening.mov?dl=0
Plus la trajectoire est lente (20s ici), plus le décalage est important et assez rapidement celui-ci implique que les sources retardataires doivent passer rapidement de l'autre côté lorsque la source 1 passe au centre. Cela fait donc de sauts abruptes qui s'entendent très clairement:
https://www.dropbox.com/s/4t9kpz3rzkroyy0/Saut%20de%20sources.mov?dl=0
Vous remarquerez également un comportement étrange et différent entre les deux vidéos: le premier termine sa trajectoire en se positionnant sur le pourtour extérieur, alors que le second le fait sur le centre! Pourquoi une telle différence comportementale?

**Comment by vberthiaume** [comment]
Je regarde ça pour la désolidarisation, mais pour ce qui est des différents points de fin des trajectoires, c'est du au choix du paramêtre dampening. À .50, la trajectoire se termine à 50% de l'élévation initiale, à .9 elle se termine à 10% de l'élévation initiale.

**Comment by vberthiaume** [comment]
Dans mes expérimentations, je remarque que le problème de désolidarisation est surtout à l'écriture du pendule. À la lecture, ça semble mieux, ou même parfait... est-ce que c'est comme ça chez vous?

**Comment by vberthiaume** [comment]
J'ai passé beaucoup de temps sur ce problème, et c'est beaucoup mieux. J'ai encore quelques problèmes une fois de temps à autres, laissez-moi savoir si c'est encore problématique pour vous.
