### ISSUE TITLE
Symmetric X et Symmetric Y dans ZirkOSC?

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ZirkOSC#82]
Pourquoi n'a-t-on pas les modes Symmetric X et Symmetric Y dans ZirkOSC?

**Comment by vberthiaume** [comment]
Simplement parce que ça n'a pas été demandé! C'est probablement assez facile à implémenter. Je m'y mets?

**Comment by Normandeau** [comment]
Oui parce que je me suis rendu compte que ça peut être utile pour gérer des sons stéréophoniques dans le dôme. Je n'avais pas réalisé que nous n'avions pas cela dans le ZirkOSC (décidément une semaine pleine de révélations)!
