### ISSUE TITLE
Azimuth Span n'est pas assez clair

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ZirkOSC#83]
Ceci est peut-être juste un détail.
Détail graphique: le Azimuth Span n'est pas assez clair:
Parfois on ne le voit pas du tout:
![azimuth span invisible](https://cloud.githubusercontent.com/assets/8959779/10765883/ded82f84-7ccc-11e5-971c-fa3a8b6fdf0e.jpg)
Parfois, on ne le voit pas à la bonne place, par exemple lorsque les deux sources ne sont pas à la même élévation, on peut penser qu'il y a une erreur car on vient de bouger le Span de la source 1, mais c'est la source 2 qui s'affiche (car on ne voit pas l'affichage de la source 1):
![azimuth span pas a la la bonne place](https://cloud.githubusercontent.com/assets/8959779/10765933/18d95820-7ccd-11e5-9ea4-6fbd5cde712e.jpg)
Bien évidemment lorsqu'on ajoute l'Elevation, tout devient clair.
Peut-être une note dans le manuel?
![azimuth elevation ok](https://cloud.githubusercontent.com/assets/8959779/10766060/97a9eff2-7ccd-11e5-9937-d8018b50dcc3.jpg)

**Comment by vberthiaume** [comment]
Dans le fond la ligne était là, mais elle était de la même largeur que le cercle qui indique la sélection de la source. J'ai mix la ligne d'azimuth plus large, laissez-moi savoir si c'est assez visible. Ou si c'est trop gros et ça fait laid...! C'est super facile à changer.

**Comment by Normandeau** [comment]
Euh! et on fait comment? On l'imagine? Ou on télécharge à nouveau la version 3.09?

**Comment by vberthiaume** [comment]
haha ça sera dans la version 3.10, qui s'en vient bientôt!

**Comment by vberthiaume** [comment]
Voici ce dont ça a l'air: 

![image](https://cloud.githubusercontent.com/assets/3721265/10914654/54c7a87e-8221-11e5-8dfc-3a20cffe5148.png)

Qu'est-ce que vous en pensez?

**Comment by Normandeau** [comment]
C’est cuuuuuuuute!


> Le 2015-11-03 à 11:52, Vincent Berthiaume <notifications@github.com> a écrit :
> 
> Voici ce dont ça a l'air:
> 
>  <https://cloud.githubusercontent.com/assets/3721265/10914654/54c7a87e-8221-11e5-8dfc-3a20cffe5148.png>
> Qu'est-ce que vous en pensez?
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/GRIS-UdeM/ZirkOSC/issues/83#issuecomment-153414717>.
> 

Bonne journée

•••••••••••••••••••••••••••••••••••••••
Robert Normandeau
Vice-doyen aux études en création et technologie
Professeur titulaire de composition électroacoustique
Faculté de musique, B-660, 343-6111 poste 3486
Université de Montréal
http://www.musique.umontreal.ca/personnel/normandeau_r.html

**Comment by AlexisLT** [comment]
Oui, c'est plus clair comme ça.
