### ISSUE TITLE
Dampening et Deviation: uniformisation des interfaces avec ZirkOSC

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ZirkOSC#91]
Ce serait bien d'uniformiser les interfaces d'Octogris et de ZirkOSC pour le Pendulum (et pour les trajectoires communes en général. J'aime bien le resserrement des Text Box dans ZirkOSC). Dampening et Deviation sont inversés notamment (je préfère l'ordre d'Octogris) et le bouton Ready est à gauche sur le premier et à droite sur le second (je préfère aussi la position d'Octogris. À gauche Octogris, à droite, ZirkOSC:

![capture d ecran 2015-11-29 a 09 38 49](https://cloud.githubusercontent.com/assets/8959779/11457871/9dee2170-9682-11e5-806b-84b5cd51afa7.jpg)

**Comment by vberthiaume** [comment]
automatiquement fait sur spatgris
