### ISSUE TITLE
Implanter l'iPad dans ZirkOSC

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ZirkOSC#94]
Cela fonctionne vraiment très bien dans Octogris. C'est, et de loin, la meilleure interface. L’interaction est très précise, les courbes écrites sont très fidèles et c'est très agréable à utiliser. Comment se fait-il qu'on n'arrive pas à cette précision avec les autres interfaces? Le iPad fait la démonstration que ce n'est pas le séquenceur qui est en défaut, mais la communication entre les interfaces et le séquenceur lorsqu'on utilise la Leap ou le Joystick.
Dans d l'ordre, le Joystick, la Leap et le iPad:

![capture d ecran 2015-11-29 a 11 34 39](https://cloud.githubusercontent.com/assets/8959779/11458423/9b0dd0a8-968d-11e5-8200-959e8837967c.jpg)

**Comment by vberthiaume** [comment]
fonctionne sur spatgris!
